### ISSUE TITLE
cannot add execution node

### ISSUE THREAD

**Issue by mehdia4ever** [fitbeard/awx-without-k8s#49]
Cannot add execution node manualy after upgrade awx to 22 version.

![image](https://user-images.githubusercontent.com/73796056/231494169-614e6ff0-57ed-419f-9570-dfb71da7c8dd.png)

Thank you

**Comment by fitbeard** [comment]
In fully automated and Kubernetes based install UI button for adding new executors is disabled by design. It’s not a bug. You can override this using cli: https://github.com/fitbeard/awx-without-k8s#add-execution-nodes-to-the-awx-cluster-manually … or run playbook which will add new nodes automatically… or you can use manual peering: https://github.com/fitbeard/awx-without-k8s#start-installation-aap-like-with-manual-peering like in paid ansible automation platform version. But first of all start reading documentation in upstream and in this repository.

**Comment by mehdia4ever** [comment]
thank's
