### ISSUE TITLE
AWX cannot read extra vars

### ISSUE THREAD

**Issue by mehdia4ever** [fitbeard/awx-without-k8s#54]
I used the latest version of your AWX, but a have a problem when i run the job.

when define a variable in AWX (tower_user_name) in the example.

![image](https://github.com/fitbeard/awx-without-k8s/assets/73796056/9c63d770-40f1-45db-8b56-1a672840e7f7)

the variable cannot be read.

![image](https://github.com/fitbeard/awx-without-k8s/assets/73796056/65e1772b-d9fb-495b-ab2d-7965d3578011)

**Comment by mehdia4ever** [comment]
ping @fitbeard

**Comment by fitbeard** [comment]
What does this have to do with this version? Does it work on an unmodified k8s install? It's not the first time you've come here with questions related to the basic operations of AWX. Why?

**Comment by mehdia4ever** [comment]
Sorry but that is not a basic question,  why you are telling me that is am running  in K8s ? 
No, am running in docker with the latest, your project is callled awx without k8s so why this question ?
I resume my problem, when i run job without extra variable, it works !
But, when i but variable in ansible (see the pictures ) it doesn’t take this variable.
If you have any ideas.
Thank you in advance

**Comment by fitbeard** [comment]
I'm not saying that you are running on k8s. I'm asking does it work on an unmodified official k8s installation? I'm still does not understand how extra variable problem is related to this install method because this is not the place for such a issues. From two redacted screenshots it is impossible understand how your credentials looks and why extra variable value should be used for credentials.
